#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pizza_Calculator.Resource", IsApplication=true)]

namespace Pizza_Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int button1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int button2 = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int checkBox1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int editText1 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int editText2 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int editText3 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int editText4 = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int listView1 = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int relativeLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView3 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textView4 = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int tvHome = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tvName = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int quantity = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int quantityPcs = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int yES = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int youEatPizzaEdge = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
